server:
  port: 8877
  servlet:
    context-path: /api/v1/activiti
    session:
      cookie:
        name: BIUSID
spring:
  application:
    name: activiti
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.10.50.198:5432/iep?currentSchema=activiti
    username: product
    password: product123456
    #url: jdbc:postgresql://localhost:5432/iep?currentSchema=activiti
    #username: postgres
    #password: postgres
    druid:
      initialSize: 5
      minIdle: 5
      maxWait: 60000
      maxActive: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  servlet:
    multipart:
      enabled: true
      #文件上传大小限制
      max-file-size: 500MB
      max-request-size: 500MB
  activiti:
      #每次应用启动时不用都检查Activiti表是否存在及版本是否匹配，以提升应用启动速度
      database-schema-update: false
      check-process-definitions: false
      #设置历史数据保存级别为最高，便于历史数据的追溯
      history-level: full
file:
  #文件静态资源访问目录
  static-access-path: /activitiUpload/uploads/
  #文件静态资源存储目录
  save-path-unix: /tmp/activitiUpload/
  save-path-windows: d://activitiUpload/
logging:
  path: ./logs
  level:
    #com.th.business: debug
    #com.th.ox.cleaver.activiti: debug
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.th.multiplanning.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #返回Map时字段值为null时也调用setter
    callSettersOnNulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
shiro:
#多规业务有关的配置
drawing-case-code:
  #控规用地规划
  kg: TM3010304
  #土地利用规划
  zg: GT200501
  #土地利用现状
  xz: GT200107
#空间参考系
spatial-reference: 4490